CREATE TABLE patients (
    id VARCHAR(64) PRIMARY KEY,
    birthdate DATETIME,
    deathdate DATETIME,
    ssn VARCHAR(20),
    drivers VARCHAR(50),
    passport VARCHAR(50),
    prefix VARCHAR(20),
    first VARCHAR(50),
    middle VARCHAR(50),
    last VARCHAR(50),
    suffix VARCHAR(20),
    maiden VARCHAR(50),
    marital VARCHAR(20),
    race VARCHAR(50),
    ethnicity VARCHAR(50),
    gender VARCHAR(10),
    birthplace VARCHAR(100),
    address VARCHAR(100),
    city VARCHAR(50),
    state VARCHAR(20),
    county VARCHAR(50),
    fips VARCHAR(20),
    zip VARCHAR(10),
    lat DECIMAL(10, 7),
    lon DECIMAL(10, 7),
    healthcare_expenses DOUBLE,
    healthcare_coverage DOUBLE,
    income DOUBLE
);
